name: robot
# on:
#   push:
#     branches:
#       - master
on:
  workflow_dispatch:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # - name: Use Node@18.x # 步骤2
      #   uses: actions/setup-node@v1 # 作用：安装nodejs
      #   with:
      #     node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.15.1

      - name: Set node version to ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'pnpm'

      - name: Install
        run: pnpm install

      # - name: Build
      #   run: pnpm build

      # 运行脚本
      - name: 运行脚本
        run: pnpm run dev
        env:
          OPENAI_API_KEY: ${{ secrets.WX_COMPANY_ID }}
